trigger:
- main

variables:
  dockerHubNamespace: shawntzx
  imageName: spamclassifier_app
  azureServiceConnection: AzureAppServiceConnection
  appServiceName: my-spamclassifier-app  # Replace with your actual App Service name

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubConnection'
        repository: '$(dockerHubNamespace)/$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/docker/Dockerfile'
        tags: |
          $(Build.BuildId)

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToAzure
    displayName: Deploy to Azure App Service
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebAppContainer@1
      inputs:
        azureSubscription: $(azureServiceConnection)
        appName: $(appServiceName)
        imageName: '$(dockerHubNamespace)/$(imageName):$(Build.BuildId)'
        startupCommand: ''
