trigger:
- main

variables:
  dockerHubNamespace: your-docker-hub-namespace
  imageName: your-image-name
  azureServiceConnection: your-azure-service-connection

stages:
- stage: Build
  jobs:
  - job: BuildAndPush
    displayName: Build and Push Docker Image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHubConnection'
        repository: '$(dockerHubNamespace)/$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/docker/Dockerfile'
        tags: |
          $(Build.BuildId)

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployToAzure
    displayName: Deploy to Azure App Service
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: $(azureServiceConnection)
        appName: your-app-service-name
        imageName: '$(dockerHubNamespace)/$(imageName):$(Build.BuildId)'
        startupCommand: ''
